name: $(VersionMajor).$(VersionMinor).$(VersionRevision)

trigger:
  branches:
    include:
    - 1.12.2
  paths:
    include:
    - src
pr: none

pool:
  name: Default
  demands: InnoSetup
#  vmImage: windows-latest

resources:
  repositories:
  - repository: MasterRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/PixelmonInformation

variables:
- name: ApplicationName
  value: 'PixelmonInformation'

stages:
- template: azure-pipelines-build.yml
  parameters:
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    PixelmonVersion: '8.4.0'

- template: azure-pipelines-deploy.yml
  parameters:
    DeploymentType: Beta
    DependsOn: build
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderBeta)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)

- template: azure-pipelines-deploy.yml
  parameters:
    DeploymentType: Production
    DependsOn: Beta
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderProduction)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)
