parameters:
- name: DeploymentType
  displayName: Type of Deployment Stage
  type: string
  values:
  - Beta
  - Production
- name: DependsOn
  displayName: Depends On
  type: string
- name: ApplicationName
  type: string
- name: PublishFolder
  type: string
- name: RepositoryFolder
  type: string
- name: GitEmail
  type: string
- name: GitUsername
  type: string
