parameters:
- name: ApplicationName
  type: string
- name: PublishFolder
  type: string

stages:
- stage: build
  displayName: Build and Publish

  jobs:
  - job: build
    displayName: Build and Publish
    workspace:
      clean: all

    steps:
    - task: PowerShell@2
      displayName: Write Build Parameters
      #condition: contains(variables['system.debug'], 'true')
      inputs:
        targetType: inline
        script: |
          Write-Host "ApplicationName: ${{parameters.ApplicationName}}"
          Write-Host "PublishFolder: ${{parameters.PublishFolder}}"
        pwsh: true
